
services:
  api:
    build:
      context: ./
    ports:
      - "${PORT}:3000"
    environment:
      - DB_PORT=${DB_INTERNAL_PORT}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - .env:/app/.env
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongo_db
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      # - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_PORT=${DB_INTERNAL_PORT}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"

  k6:
    image: grafana/k6:latest
    container_name: k6_load_test
    environment:
      - BASE_URL=http://api:3000
    volumes:
      - ./performance:/performance
    command: run /performance/k6-test.js
    depends_on:
      - api

volumes:
  mongo_data:
    driver: local
